server: 
  port: 7901
spring: 
  application:
    name: microservice-consumer-movie
eureka: 
  client: 
    healthcheck: 
      enabled: true
    serviceUrl: 
      defaultZone: http://admin:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true