server: 
  port: 7901
spring: 
  application:
    name: microservice-provider-user-v1
  jpa: 
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level: 
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.gu: DEBUG
eureka: 
  client: 
    healthcheck: 
      enabled: true
    serviceUrl: 
      defaultZone: http://admin:root@localhost:8761/eureka  #http://peer1:8762/eureka/,http://peer2:8763/eureka/ 
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name};${spring.application.instance_id;${server.port};
    metadata-map:
      zone: ABC #eureka可以理解的元数据
      gulingfeng: BBC #不会影响客户端行为
#    appname: User-APPNAME-BYSELF
#    status-page-url: http://localhost:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号