spring: 
  application:
    name: microservice-consumer-movie-ribbon
server: 
  port: 8010
eureka: 
  client: 
    healthcheck: 
      enabled: true
    serviceUrl: 
      defaultZone: http://admin:root@localhost:8761/eureka
  instance:
    prefer-ip-address: true
microservice-provider-user: 
  ribbon: 
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #com.netflix.loadbalancer.WeightedResponseTimeRule