spring:
  application:
    name: microservice-gateway-zuul
server: 
  port: 8040
eureka: 
  client: 
    service-url:
      defaultZone: http://admin:root@localhost:8761/eureka  #http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  prefix: /api  #前缀 http://192.168.1.5:8040/api/microservice-provider-user/simple/1
  